### ISSUE TITLE
The board is missing a min-height rule

### ISSUE THREAD

**Issue by kleinlikecalvin** [kleinlikecalvin/tic-tac-toe#2]
![Screen Shot 2023-02-04 at 7 47 35 AM](https://user-images.githubusercontent.com/63431649/216776729-7bc073a5-7976-46f3-97b2-fa1758ce72ed.png)

**Comment by walston** [comment]
I know this issue title is self explanatory, but a screenshot can provide some context later on.

**Comment by kleinlikecalvin** [comment]
resolved
